sudo: required
services:
  - docker

before_install:
  - docker build -t pamhimani/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true pamhimani/react-test npm test 

after_success:
  - docker build -t pamhimani/multi-client ./client
  - docker build -t pamhimani/multi-nginx ./nginx
  - docker build -t pamhimani/multi-server ./server
  - docker build -t pamhimani/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take these images and push to dockerhub
  - docker push pamhimani/multi-client
  - docker push pamhimani/multi-nginx
  - docker push pamhimani/multi-server
  - docker push pamhimani/multi-worker

